// <auto-generated />
namespace TCPChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _Chats_Clients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Chats_Clients));
        
        string IMigrationMetadata.Id
        {
            get { return "202011131729304__Chats_Clients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
